version: "3.8"

services:
  api:
    image: node:18-alpine
    env_file: .env
    working_dir: /app
    command: npm start
    ports:
      - "$UI_PORT:$UI_PORT"
      - "$API_PORT:$API_PORT"
      - "$WEBSOCKET_PORT:$WEBSOCKET_PORT"
    volumes:
      - ${PWD}:/app
