version: "3.6"

services:
  services:
    container_name: greedy-http
    build: .
    env_file:
      - ${PWD}/.env
    ports:
      - ${GREEDY_HTTP_API_PORT}:${GREEDY_HTTP_API_PORT}
      - ${GREEDY_HTTP_UI_PORT}:${GREEDY_HTTP_UI_PORT}
      - ${GREEDY_HTTP_WS_PORT}:${GREEDY_HTTP_WS_PORT}