name: Publish to NPM

on: push

jobs:
  test:
    name: "Test & Publish 🚀"
    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: fregante/setup-git-user@v1
      - run: npm ci
      - run: npm test
      - run: npm run release
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - run: git push --follow-tags origin $(git branch)
